CC      := gcc
CFLAGS  := -std=c99 -Wall -Wextra -O2 -g -D_POSIX_C_SOURCE=200809L
LDFLAGS ?=

# OpenSSL support (can disable with CS_NO_TLS=1)
ifndef CS_NO_TLS
	CFLAGS += $(shell pkg-config --cflags openssl 2>/dev/null)
	LDFLAGS += $(shell pkg-config --libs openssl 2>/dev/null || echo "-lssl -lcrypto")
else
	CFLAGS += -DCS_NO_TLS
endif
DEPFLAGS ?= -MMD -MP
AR      := ar
ARFLAGS := rcs

SRCDIR  := src
OBJDIR  := obj
BINDIR  := bin

CS_SRCS := cs_value.c cs_lexer.c cs_parser.c cs_vm.c cs_stdlib.c cs_event_loop.c cs_net.c cs_tls.c cs_http.c
CS_OBJS := $(patsubst %.c,$(OBJDIR)/%.o,$(CS_SRCS))

CLI_SRCS := main.c
CLI_OBJS := $(patsubst %.c,$(OBJDIR)/%.o,$(CLI_SRCS))

LIB := $(BINDIR)/libcupidscript.a
BIN := $(BINDIR)/cupidscript

API_TEST_BIN := $(BINDIR)/c_api_tests
API_TEST_OBJS := $(OBJDIR)/c_api_tests.o

# Dependency files (auto-generated by the compiler).
DEPS := $(CS_OBJS:.o=.d) $(CLI_OBJS:.o=.d) $(API_TEST_OBJS:.o=.d)

# If objects are built with gcov instrumentation, the link step must also include
# coverage flags (otherwise __gcov_* symbols are undefined).
COVERAGE_LDFLAGS :=
ifneq (,$(filter --coverage,$(CFLAGS)))
	COVERAGE_LDFLAGS += --coverage
endif
ifneq (,$(filter -fprofile-arcs,$(CFLAGS)))
	COVERAGE_LDFLAGS += -fprofile-arcs
endif
ifneq (,$(filter -ftest-coverage,$(CFLAGS)))
	COVERAGE_LDFLAGS += -ftest-coverage
endif

.PHONY: all clean dirs test

all: dirs $(LIB) $(BIN) $(API_TEST_BIN)

# Auto-generated header dependencies.
# Note: These .d files don't exist on a fresh tree; the rules below will bootstrap them.
-include $(DEPS)

dirs:
	@mkdir -p $(OBJDIR) $(BINDIR)

# Bootstrap dependency generation: if a .d is missing, generate it.
# Use `-MM` so GCC emits deps and exits (no compile/link).
$(OBJDIR)/%.d: $(SRCDIR)/%.c | dirs
	@$(CC) $(CFLAGS) -MM -MP -MF $@ -MT $(OBJDIR)/$*.o -Isrc $<

$(OBJDIR)/c_api_tests.d: tests/c_api_tests.c | dirs
	@$(CC) $(CFLAGS) -MM -MP -MF $@ -MT $(OBJDIR)/c_api_tests.o -Isrc $<

$(OBJDIR)/%.o: $(SRCDIR)/%.c
	$(CC) $(CFLAGS) $(DEPFLAGS) -Isrc -c $< -o $@

$(LIB): $(CS_OBJS)
	$(AR) $(ARFLAGS) $@ $^

$(BIN): $(CS_OBJS) $(CLI_OBJS)
	$(CC) $(CFLAGS) -Isrc $^ -o $@ $(COVERAGE_LDFLAGS) $(LDFLAGS) -lz -lm

$(OBJDIR)/c_api_tests.o: tests/c_api_tests.c
	$(CC) $(CFLAGS) $(DEPFLAGS) -Isrc -c $< -o $@

$(API_TEST_BIN): $(CS_OBJS) $(API_TEST_OBJS)
	$(CC) $(CFLAGS) -Isrc $^ -o $@ $(COVERAGE_LDFLAGS) $(LDFLAGS) -lz -lm

clean:
	rm -rf $(OBJDIR) $(BINDIR)


test: all $(API_TEST_BIN)
	@bash tests/run_tests.sh
