.TH NOTES
.SH NOTES ABOUT CUPIDFM
.SS "FAULTY NAVIGATE_RIGHT"
If the user tries to navigate right when the selected item is not a directory,
the cursor gets reset even though no action has been performed. I assume that
the same happens with navigate left when in the root directory, but I didn't
test it.
.BR Solution :
Making the
.I CursorAndSlice
reset inside the navigation function might solve this issue. Returning a
boolean to tell the caller either an action has been performed or not might
also work.

